/**
 * 🏛️ RJ BUSINESS SOLUTIONS — FUNNEL ARCHITECT (LIVE LLM ENGINE)
 * True generative funnel construction — nothing hard-coded, nothing templated.
 *
 * Pipeline (each stage is a separate live LLM call):
 *   STAGE 1 — STRATEGY: the LLM analyzes the operator's prompt and designs a
 *             bespoke funnel strategy: audience psychology, hook/angle, brand
 *             system, and a proper multi-page chain (4–5 pages) where every
 *             page has a defined conversion job and hands off to the next.
 *   STAGE 2 — PAGE FORGE: every page in the chain is generated by its own
 *             dedicated LLM call with full strategy context + summaries of the
 *             pages already built, so copy, design and CTAs flow as one
 *             continuous narrative. Full standalone HTML per page.
 *   STAGE 3 — CAMPAIGN: a 3-email nurture sequence + SMS follow-ups written
 *             against the same strategy.
 *   STAGE 4 — VALIDATION GATE: structural + uniqueness checks. Pages that are
 *             thin, unlinked, or near-duplicates FAIL the gate and the result
 *             is flagged — no silent cheap output.
 *
 * Provider chain (first configured wins):
 *   1. Any OpenAI-compatible endpoint (OpenAI, GenSpark LLM proxy, LiteLLM,
 *      vLLM, Groq-OpenAI, LM Studio…) — config.openaiApiKey/openaiBaseUrl
 *   2. Google Gemini            — config.googleApiKey
 *   3. OpenRouter               — config.openrouterApiKey
 */

import { getAppConfig } from './config';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export interface LLMEndpoint {
  name: string;
  kind: 'openai' | 'gemini';
  url: string;      // base URL for openai-kind; full model URL built for gemini
  key: string;
  model: string;
}

export interface FunnelStrategy {
  businessName: string;
  vertical: string;
  offer: string;
  audience: string;
  bigIdea: string;
  angle: string;
  palette: { primary: string; secondary: string; accent: string; background: string; textOnDark: string };
  fonts: { heading: string; body: string };
  voice: string;
  pages: Array<{
    slug: string;          // e.g. "/", "/qualify", "/book", "/thank-you"
    title: string;
    purpose: string;       // the conversion job of this page
    keyElements: string[]; // sections the page must contain
    ctaLabel: string;
    nextSlug: string | null;
  }>;
}

export interface ArchitectedPage {
  slug: string;
  title: string;
  purpose: string;
  html: string;
  wordCount: number;
  sections: number;
}

export interface ArchitectedCampaign {
  emails: Array<{ day: number; subject: string; preheader: string; body: string }>;
  sms: Array<{ day: number; message: string }>;
}

export interface ValidationCheck { name: string; pass: boolean; detail: string }

export interface FunnelValidation {
  checks: ValidationCheck[];
  passed: boolean;
  score: number;          // 0-100
  uniquenessPct: number;  // min pairwise content distance across pages
}

export interface ArchitectedFunnel {
  strategy: FunnelStrategy;
  pages: ArchitectedPage[];
  campaign: ArchitectedCampaign;
  validation: FunnelValidation;
  provider: string;
  model: string;
  totalLatencyMs: number;
  llmCalls: number;
}

export type ArchitectProgress = (stage: string, pct: number, detail?: string) => void;

// ─────────────────────────────────────────────────────────────────────────────
// Provider resolution
// ─────────────────────────────────────────────────────────────────────────────

export function resolveEndpoints(): LLMEndpoint[] {
  const cfg = getAppConfig();
  const endpoints: LLMEndpoint[] = [];
  if (cfg.openaiApiKey && cfg.openaiBaseUrl) {
    endpoints.push({ name: 'OpenAI-Compatible', kind: 'openai', url: cfg.openaiBaseUrl.replace(/\/$/, ''), key: cfg.openaiApiKey, model: cfg.openaiModel || 'gpt-5-mini' });
  }
  if (cfg.googleApiKey) {
    endpoints.push({ name: 'Google Gemini', kind: 'gemini', url: 'https://generativelanguage.googleapis.com/v1beta/models', key: cfg.googleApiKey, model: 'gemini-2.0-flash' });
  }
  if (cfg.openrouterApiKey) {
    endpoints.push({ name: 'OpenRouter', kind: 'openai', url: 'https://openrouter.ai/api/v1', key: cfg.openrouterApiKey, model: 'anthropic/claude-3.5-sonnet' });
  }
  return endpoints;
}

async function callLLM(ep: LLMEndpoint, system: string, user: string, maxTokens = 9000): Promise<string> {
  if (ep.kind === 'gemini') {
    const res = await fetch(`${ep.url}/${ep.model}:generateContent?key=${ep.key}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        systemInstruction: { parts: [{ text: system }] },
        contents: [{ role: 'user', parts: [{ text: user }] }],
        generationConfig: { maxOutputTokens: maxTokens },
      }),
    });
    if (!res.ok) throw new Error(`Gemini ${res.status}: ${(await res.text()).slice(0, 200)}`);
    const data = await res.json();
    const text = data.candidates?.[0]?.content?.parts?.map((p: { text?: string }) => p.text || '').join('');
    if (!text) throw new Error('Empty Gemini response');
    return text;
  }
  // OpenAI-compatible
  const res = await fetch(`${ep.url}/chat/completions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${ep.key}` },
    body: JSON.stringify({
      model: ep.model,
      messages: [
        { role: 'system', content: system },
        { role: 'user', content: user },
      ],
      max_completion_tokens: maxTokens,
    }),
  });
  if (!res.ok) throw new Error(`${ep.name} ${res.status}: ${(await res.text()).slice(0, 200)}`);
  const data = await res.json();
  const text = data.choices?.[0]?.message?.content;
  if (!text) throw new Error(`Empty ${ep.name} response`);
  return text;
}

// ─────────────────────────────────────────────────────────────────────────────
// Robust extraction
// ─────────────────────────────────────────────────────────────────────────────

function extractJSON<T>(raw: string): T {
  let s = raw.trim();
  // Strip markdown fences
  s = s.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '');
  // Isolate outermost object
  const start = s.indexOf('{');
  const end = s.lastIndexOf('}');
  if (start === -1 || end === -1) throw new Error('No JSON object in LLM response');
  s = s.slice(start, end + 1);
  return JSON.parse(s) as T;
}

function extractHTML(raw: string): string {
  let s = raw.trim();
  s = s.replace(/^```(?:html)?\s*/i, '').replace(/\s*```$/i, '');
  const start = s.search(/<!DOCTYPE html/i);
  if (start >= 0) {
    const end = s.lastIndexOf('</html>');
    if (end > start) return s.slice(start, end + 7);
    return s.slice(start);
  }
  const hStart = s.search(/<html/i);
  if (hStart >= 0) return '<!DOCTYPE html>\n' + s.slice(hStart);
  throw new Error('No HTML document in LLM response');
}

// ─────────────────────────────────────────────────────────────────────────────
// Stage prompts
// ─────────────────────────────────────────────────────────────────────────────

const STRATEGY_SYSTEM = `You are an elite direct-response funnel strategist and conversion copy chief (think Russell Brunson's funnel architecture + Ogilvy's positioning discipline). You design bespoke, industry-specific funnels — never generic. You respond with STRICT JSON only, no markdown, no commentary.`;

function strategyPrompt(userPrompt: string, fallbackBiz: string): string {
  return `Design a complete, UNIQUE conversion funnel strategy for this request:

"""${userPrompt}"""

${fallbackBiz ? `If no business name is given, use: ${fallbackBiz}` : ''}

Rules:
- Design a proper funnel CHAIN of 4 pages: an offer/landing page, a qualification or value step (quiz, calculator, case-study, or VSL page — choose what fits THIS business), a capture/booking page, and a thank-you/next-steps page. Choose slugs that fit.
- Every page must have ONE conversion job and hand off to the next page (nextSlug).
- The brand palette must honor any colors the user asked for (as hex), else derive a palette that fits the business's industry psychology.
- The copy angle must be specific to this business & audience — reference their world, their pains, their language. NO generic marketing filler.
- Compliance: this platform serves tax/financial verticals — never promise guaranteed refunds/outcomes; use compliant phrasing.

Return STRICT JSON exactly in this shape:
{
  "businessName": "...",
  "vertical": "...",
  "offer": "...",
  "audience": "one-sentence psychographic portrait",
  "bigIdea": "the one belief this funnel installs",
  "angle": "the specific hook/mechanism",
  "palette": { "primary": "#hex", "secondary": "#hex", "accent": "#hex", "background": "#hex", "textOnDark": "#hex" },
  "fonts": { "heading": "font stack", "body": "font stack" },
  "voice": "tone description",
  "pages": [
    { "slug": "/", "title": "...", "purpose": "...", "keyElements": ["...","...","...","...","..."], "ctaLabel": "...", "nextSlug": "/..." },
    { "slug": "/...", "title": "...", "purpose": "...", "keyElements": ["..."], "ctaLabel": "...", "nextSlug": "/..." },
    { "slug": "/...", "title": "...", "purpose": "...", "keyElements": ["..."], "ctaLabel": "...", "nextSlug": "/thank-you" },
    { "slug": "/thank-you", "title": "...", "purpose": "...", "keyElements": ["..."], "ctaLabel": "...", "nextSlug": null }
  ]
}`;
}

const PAGE_SYSTEM = `You are a world-class landing page designer-developer who hand-crafts premium, conversion-engineered pages. You write COMPLETE standalone HTML documents with embedded <style>. Modern glassmorphism, hardware-accelerated CSS, mobile-responsive, real long-form conversion copy (never lorem ipsum, never placeholder text, never "[insert X]"). You respond with ONLY the HTML document — no markdown fences, no commentary.`;

function pagePrompt(strategy: FunnelStrategy, page: FunnelStrategy['pages'][number], builtSummaries: string[]): string {
  const p = strategy.palette;
  return `Build page ${page.slug} of the "${strategy.businessName}" funnel.

FUNNEL STRATEGY CONTEXT:
- Business: ${strategy.businessName} (${strategy.vertical})
- Offer: ${strategy.offer}
- Audience: ${strategy.audience}
- Big idea: ${strategy.bigIdea}
- Angle: ${strategy.angle}
- Voice: ${strategy.voice}
- Brand palette: primary ${p.primary}, secondary ${p.secondary}, accent ${p.accent}, background ${p.background}, text-on-dark ${p.textOnDark}
- Fonts: headings ${strategy.fonts.heading}; body ${strategy.fonts.body}

THIS PAGE'S JOB: ${page.purpose}
PAGE TITLE: ${page.title}
REQUIRED SECTIONS: ${page.keyElements.join(' · ')}
PRIMARY CTA LABEL: "${page.ctaLabel}"
${page.nextSlug ? `CTA DESTINATION: every primary CTA must be <a href="${page.nextSlug}"> (relative link to the next funnel step).` : 'This is the final page — no forward CTA; give next-steps instructions instead.'}

${builtSummaries.length ? `PAGES ALREADY BUILT (maintain narrative continuity, do NOT repeat their copy):\n${builtSummaries.map((s, i) => `${i + 1}. ${s}`).join('\n')}` : ''}

HARD REQUIREMENTS:
- Complete standalone HTML5 document (<!DOCTYPE html> … </html>) with ALL CSS embedded in one <style> block. No external assets, no JS frameworks (vanilla inline JS allowed for micro-interactions).
- Use the brand palette via CSS custom properties. Glassmorphism cards, gradient depth, generous whitespace, micro-animation on hover.
- Long-form REAL copy specific to ${strategy.vertical}: concrete pains, concrete numbers, objection handling. Minimum 350 words of visible copy on content pages (thank-you page may be shorter but must include a 3-step "what happens next").
- If this is a capture/booking step, include a working <form> with name/email/phone fields and the CTA as submit, plus trust/compliance microcopy (SMS consent, privacy).
- Footer: "© ${new Date().getFullYear()} ${strategy.businessName} · Powered by RJ Business Solutions". Include compliant disclaimer if offer touches tax/credit outcomes.
- Output ONLY the HTML document.`;
}

const CAMPAIGN_SYSTEM = `You are a direct-response email/SMS copywriter. STRICT JSON only, no markdown.`;

function campaignPrompt(strategy: FunnelStrategy): string {
  return `Write the launch nurture campaign for the "${strategy.businessName}" funnel (offer: ${strategy.offer}; audience: ${strategy.audience}; angle: ${strategy.angle}; voice: ${strategy.voice}).

Return STRICT JSON:
{
  "emails": [
    { "day": 0, "subject": "...", "preheader": "...", "body": "full email body with [First Name] merge tag and [Funnel Link]" },
    { "day": 2, "subject": "...", "preheader": "...", "body": "..." },
    { "day": 5, "subject": "...", "preheader": "...", "body": "..." }
  ],
  "sms": [
    { "day": 0, "message": "≤300 chars, [First Name] + [Short Link], ends with 'Reply STOP to opt out'" },
    { "day": 3, "message": "..." }
  ]
}
Rules: every email ≥120 words of real persuasive copy, CAN-SPAM footer placeholder [Unsubscribe Link], no guaranteed-outcome claims.`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Validation gate
// ─────────────────────────────────────────────────────────────────────────────

function stripToText(html: string): string {
  return html
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * 5-word shingle sets — measures actual copied phrasing between pages, not
 * incidental English letter overlap (character n-grams false-positive badly).
 */
function shingleSet(text: string, n = 5): Set<string> {
  const words = text.toLowerCase().match(/[a-z0-9']+/g) || [];
  const set = new Set<string>();
  for (let i = 0; i <= words.length - n; i++) set.add(words.slice(i, i + n).join(' '));
  return set;
}

function similarity(a: string, b: string): number {
  const sa = shingleSet(a); const sb = shingleSet(b);
  if (!sa.size || !sb.size) return 0;
  let inter = 0;
  for (const g of sa) if (sb.has(g)) inter++;
  // Containment: share of the smaller page's phrasing found in the other
  return inter / Math.min(sa.size, sb.size);
}

export function validateFunnel(strategy: FunnelStrategy, pages: ArchitectedPage[]): FunnelValidation {
  const checks: ValidationCheck[] = [];

  // 1. Chain completeness
  checks.push({
    name: 'Full page chain generated',
    pass: pages.length === strategy.pages.length && pages.length >= 4,
    detail: `${pages.length}/${strategy.pages.length} pages`,
  });

  // 2. Every page is a complete HTML doc
  const completeDocs = pages.filter((p) => /<!DOCTYPE html/i.test(p.html) && /<\/html>/i.test(p.html) && /<style[\s>]/i.test(p.html));
  checks.push({
    name: 'Complete standalone HTML documents',
    pass: completeDocs.length === pages.length,
    detail: `${completeDocs.length}/${pages.length} pages have DOCTYPE + </html> + embedded <style>`,
  });

  // 3. Chain links — each non-final page links to its nextSlug
  let linked = 0; let linkable = 0;
  for (const sp of strategy.pages) {
    if (!sp.nextSlug) continue;
    linkable++;
    const built = pages.find((p) => p.slug === sp.slug);
    if (built && built.html.includes(`href="${sp.nextSlug}"`)) linked++;
  }
  checks.push({
    name: 'Funnel chain properly linked',
    pass: linkable > 0 && linked === linkable,
    detail: `${linked}/${linkable} pages carry CTA links to their next step`,
  });

  // 4. Real long-form copy, no placeholder CONTENT.
  // NOTE: checked against visible text only — the HTML `placeholder=` input
  // attribute is legitimate UI and must not trip this gate.
  const placeholderRe = /lorem ipsum|\[insert |\{\{|\bTODO\b|\[PLACEHOLDER\]|coming soon\.{3}/i;
  const thin = pages.filter((p) => p.slug !== '/thank-you' && !/thank/i.test(p.slug) && p.wordCount < 250);
  const withPlaceholders = pages.filter((p) => placeholderRe.test(stripToText(p.html)));
  checks.push({
    name: 'Long-form real copy (no thin pages)',
    pass: thin.length === 0,
    detail: thin.length ? `Thin pages: ${thin.map((p) => `${p.slug} (${p.wordCount}w)`).join(', ')}` : `Word counts: ${pages.map((p) => `${p.slug}=${p.wordCount}`).join(', ')}`,
  });
  checks.push({
    name: 'No placeholder/lorem content',
    pass: withPlaceholders.length === 0,
    detail: withPlaceholders.length ? `Placeholders found in: ${withPlaceholders.map((p) => p.slug).join(', ')}` : 'Clean',
  });

  // 5. Lead capture form exists somewhere in the chain
  const hasForm = pages.some((p) => /<form[\s>]/i.test(p.html) && /type="email"|name="email"/i.test(p.html));
  checks.push({
    name: 'Lead capture form present in chain',
    pass: hasForm,
    detail: hasForm ? 'Form with email field found' : 'No capture form detected',
  });

  // 6. Brand palette actually used
  const paletteHits = pages.filter((p) => p.html.toLowerCase().includes(strategy.palette.primary.toLowerCase()));
  checks.push({
    name: 'Brand palette applied',
    pass: paletteHits.length >= Math.ceil(pages.length * 0.75),
    detail: `${paletteHits.length}/${pages.length} pages use primary ${strategy.palette.primary}`,
  });

  // 7. Uniqueness — pages must not be near-duplicates of each other
  let maxSim = 0;
  for (let i = 0; i < pages.length; i++) {
    for (let j = i + 1; j < pages.length; j++) {
      maxSim = Math.max(maxSim, similarity(stripToText(pages[i].html), stripToText(pages[j].html)));
    }
  }
  const uniquenessPct = Math.round((1 - maxSim) * 100);
  checks.push({
    name: 'Pages are unique (not near-duplicates)',
    pass: maxSim < 0.35,
    detail: `Max shared phrasing between any two pages: ${(maxSim * 100).toFixed(1)}% (5-word shingles; must be < 35%)`,
  });

  const passedCount = checks.filter((c) => c.pass).length;
  return {
    checks,
    passed: passedCount === checks.length,
    score: Math.round((passedCount / checks.length) * 100),
    uniquenessPct,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Master orchestration
// ─────────────────────────────────────────────────────────────────────────────

export async function generateLLMFunnel(
  userPrompt: string,
  opts: { endpoints?: LLMEndpoint[]; onProgress?: ArchitectProgress; fallbackBusinessName?: string } = {}
): Promise<ArchitectedFunnel> {
  const t0 = performance.now();
  const endpoints = opts.endpoints?.length ? opts.endpoints : resolveEndpoints();
  const onProgress = opts.onProgress || (() => {});
  if (!endpoints.length) {
    throw new Error('NO_LLM_CONFIGURED');
  }

  let llmCalls = 0;
  let active: LLMEndpoint | null = null;

  // Try providers in order until one answers the strategy call
  const ask = async (system: string, user: string, maxTokens: number): Promise<string> => {
    llmCalls++;
    if (active) return callLLM(active, system, user, maxTokens);
    let lastErr: unknown;
    for (const ep of endpoints) {
      try {
        const out = await callLLM(ep, system, user, maxTokens);
        active = ep;
        return out;
      } catch (e) { lastErr = e; }
    }
    throw lastErr instanceof Error ? lastErr : new Error('All LLM providers failed');
  };

  // STAGE 1 — Strategy
  onProgress('Stage 1/4 — LLM designing bespoke funnel strategy…', 5);
  const strategyRaw = await ask(STRATEGY_SYSTEM, strategyPrompt(userPrompt, opts.fallbackBusinessName || ''), 4000);
  const strategy = extractJSON<FunnelStrategy>(strategyRaw);
  if (!strategy.pages?.length || strategy.pages.length < 3) throw new Error('Strategy stage returned an incomplete page chain');
  onProgress('Strategy locked — ' + strategy.pages.length + '-page chain designed', 15, strategy.angle);

  // STAGE 2 — Page forge (one dedicated LLM call per page)
  const pages: ArchitectedPage[] = [];
  const summaries: string[] = [];
  for (let i = 0; i < strategy.pages.length; i++) {
    const sp = strategy.pages[i];
    const pctBase = 15 + Math.round((i / strategy.pages.length) * 60);
    onProgress(`Stage 2/4 — Forging page ${i + 1}/${strategy.pages.length}: ${sp.title}`, pctBase, sp.purpose);
    const html = extractHTML(await ask(PAGE_SYSTEM, pagePrompt(strategy, sp, summaries), 14000));
    const text = stripToText(html);
    const wordCount = text.split(/\s+/).filter(Boolean).length;
    const sections = (html.match(/<section[\s>]/gi) || []).length || (html.match(/<div class="[^"]*(section|block|card)/gi) || []).length;
    pages.push({ slug: sp.slug, title: sp.title, purpose: sp.purpose, html, wordCount, sections });
    summaries.push(`${sp.slug} "${sp.title}" — ${sp.purpose}. Headline used: ${text.slice(0, 140)}…`);
  }

  // STAGE 3 — Campaign
  onProgress('Stage 3/4 — Writing nurture email & SMS campaign…', 80);
  const campaign = extractJSON<ArchitectedCampaign>(await ask(CAMPAIGN_SYSTEM, campaignPrompt(strategy), 5000));

  // STAGE 4 — Validation gate
  onProgress('Stage 4/4 — Running validation gate…', 92);
  const validation = validateFunnel(strategy, pages);

  onProgress('Complete', 100);
  return {
    strategy,
    pages,
    campaign,
    validation,
    provider: active!.name,
    model: active!.model,
    totalLatencyMs: Math.round(performance.now() - t0),
    llmCalls,
  };
}
